"""Default catalog seeded with Alside Supply Pittsburgh dealer price sheet (2026 5-11).
Material prices = Alside wholesale. Labor = 0 (each contractor sets their own labor)."""

DEFAULT_SECTIONS = [
    {"title": "Vinyl Siding", "ascend": False, "items": [
        {"name": "Conquest Dutchlap & Double 4.5\" Siding .040", "unit": "SQ", "mat": 75.71, "lab": 0},
        {"name": "Conquest Dutchlap & Double 4.5\" Arch Colors .040", "unit": "SQ", "mat": 75.71, "lab": 0},
        {"name": "Coventry D4 Dutchlap & Clapboard SDG .042", "unit": "SQ", "mat": 81.17, "lab": 0},
        {"name": "Coventry D4 Dutchlap & Clapboard SDG Arch Colors .042", "unit": "SQ", "mat": 88.10, "lab": 0},
        {"name": "Coventry D5 Dutchlap & Clapboard SDG .042", "unit": "SQ", "mat": 81.17, "lab": 0},
        {"name": "Coventry D5 Dutchlap & Clapboard SDG Arch Colors .042", "unit": "SQ", "mat": 88.10, "lab": 0},
        {"name": "Odyssey Plus Dutchlap & Double 4\" Siding .044", "unit": "SQ", "mat": 100.11, "lab": 0},
        {"name": "Odyssey Plus Dutchlap & Double 4\" Arch Colors .044", "unit": "SQ", "mat": 108.47, "lab": 0},
        {"name": "Odyssey Plus Dutchlap & Double 5\" Siding .044", "unit": "SQ", "mat": 100.11, "lab": 0},
        {"name": "Odyssey Plus Dutchlap & Double 5\" Arch Colors .044", "unit": "SQ", "mat": 108.47, "lab": 0},
        {"name": "Charter Oak Dutchlap & Double 4.5\" .046", "unit": "SQ", "mat": 113.57, "lab": 0},
        {"name": "Charter Oak Dutchlap & Double 4.5\" Arch Colors .046", "unit": "SQ", "mat": 123.40, "lab": 0},
        {"name": "Charter Oak XL Dutchlap & Double 4.5\" .046", "unit": "SQ", "mat": 117.94, "lab": 0},
        {"name": "Charter Oak XL Dutchlap & Double 4.5\" Arch Colors .046", "unit": "SQ", "mat": 127.41, "lab": 0},
        {"name": "Board and Batten Vertical Siding .050", "unit": "SQ", "mat": 113.57, "lab": 0},
        {"name": "Board and Batten Vertical Siding Arch Colors .050", "unit": "SQ", "mat": 123.40, "lab": 0},
        {"name": "Pelican Bay Scallops", "unit": "SQ", "mat": 324.90, "lab": 0},
        {"name": "Pelican Bay Shakes", "unit": "SQ", "mat": 265.20, "lab": 0},
        {"name": "Pelican Bay CapeCod Shingle", "unit": "SQ", "mat": 358.38, "lab": 0},
        {"name": "Pelican Bay Hand Split Shake", "unit": "SQ", "mat": 322.08, "lab": 0},
        {"name": "Prodigy Dutchlap DL5 Siding", "unit": "SQ", "mat": 219.90, "lab": 0},
        {"name": "Williamsport 6\" Beaded Siding", "unit": "SQ", "mat": 108.16, "lab": 0},
        {"name": "Williamsport 6\" Beaded Siding Arch Colors", "unit": "SQ", "mat": 117.52, "lab": 0},
    ]},
    {"title": "ASCEND Composite Cladding", "ascend": True, "items": [
        {"name": "ASCEND Composite Cladding 7\" Clap", "unit": "SQ", "mat": 309.64, "lab": 0},
        {"name": "ASCEND Composite Cladding 12\" B&B", "unit": "SQ", "mat": 366.96, "lab": 0},
        {"name": "ASCEND Starter Strip", "unit": "PIECE", "mat": 7.68, "lab": 0},
        {"name": "ASCEND Finish Trim", "unit": "PIECE", "mat": 7.86, "lab": 0},
    ]},
    {"title": "Soffit", "ascend": False, "items": [
        {"name": "Charter Oak solid/Aerated", "unit": "PIECE", "mat": 14.08, "lab": 0},
        {"name": "Charter Oak solid/Aerated Arch Colors", "unit": "PIECE", "mat": 15.48, "lab": 0},
        {"name": "Greenbriar Vintage Beaded Std. Colors", "unit": "PIECE", "mat": 12.33, "lab": 0},
        {"name": "2T White Only solid/Aerated", "unit": "PIECE", "mat": 9.51, "lab": 0},
    ]},
    {"title": "Standard Accessories", "ascend": False, "items": [
        {"name": "3/4\" F Channel Standard Colors", "unit": "PIECE", "mat": 7.19, "lab": 0},
        {"name": "3/4\" F Channel Architectural Colors", "unit": "PIECE", "mat": 7.57, "lab": 0},
        {"name": "Inside Corner Post Standard Colors", "unit": "PIECE", "mat": 9.84, "lab": 0},
        {"name": "Inside Corner Post Architectural Colors", "unit": "PIECE", "mat": 10.97, "lab": 0},
        {"name": "4\" Outside Corner Post Standard Colors", "unit": "PIECE", "mat": 19.69, "lab": 0},
        {"name": "4\" Outside Corner Post Architectural Colors", "unit": "PIECE", "mat": 21.58, "lab": 0},
        {"name": "1/2\" J Channel", "unit": "PIECE", "mat": 4.55, "lab": 0},
        {"name": "1/2\" J Channel Architectural Colors", "unit": "PIECE", "mat": 5.29, "lab": 0},
        {"name": "5/8\" J Channel", "unit": "PIECE", "mat": 7.28, "lab": 0},
        {"name": "5/8\" J Channel Architectural Colors", "unit": "PIECE", "mat": 8.49, "lab": 0},
        {"name": "3/4\" J Channel Standard Colors", "unit": "PIECE", "mat": 4.55, "lab": 0},
        {"name": "3/4\" J Channel Architectural Colors", "unit": "PIECE", "mat": 5.29, "lab": 0},
        {"name": "5/8\" Flexable J Channel", "unit": "PIECE", "mat": 18.09, "lab": 0},
        {"name": "45 Bay/Bow Outside Corner Post", "unit": "PIECE", "mat": 20.24, "lab": 0},
        {"name": "Finish Trim Standard Colors", "unit": "PIECE", "mat": 4.55, "lab": 0},
        {"name": "Finish Trim Architectural Colors", "unit": "PIECE", "mat": 4.92, "lab": 0},
        {"name": "3.5\" Lineal Standard Colors", "unit": "PIECE", "mat": 40.65, "lab": 0},
        {"name": "5\" Lineal Standard Colors", "unit": "PIECE", "mat": 35.21, "lab": 0},
        {"name": "Universal Starter Strip", "unit": "PIECE", "mat": 4.53, "lab": 0},
    ]},
    {"title": "Coil", "ascend": False, "items": [
        {"name": "Smooth Coil 24\"x50'", "unit": "Roll", "mat": 133.23, "lab": 0},
        {"name": "PVC Coil 24\"x50'", "unit": "Roll", "mat": 149.74, "lab": 0},
        {"name": "G8 Coil 24\"x50'", "unit": "Roll", "mat": 145.89, "lab": 0},
    ]},
    {"title": "Shutters", "ascend": False, "items": [
        {"name": "Raised Panel 15\" (Call Alside for price)", "unit": "PAIR", "mat": 0, "lab": 0},
        {"name": "Raised Panel 12\" (Call Alside for price)", "unit": "PAIR", "mat": 0, "lab": 0},
        {"name": "Louvered Panel 15\" (Call Alside for price)", "unit": "PAIR", "mat": 0, "lab": 0},
        {"name": "Louvered Panel 12\" (Call Alside for price)", "unit": "PAIR", "mat": 0, "lab": 0},
    ]},
    {"title": "Blocks and Vents", "ascend": False, "items": [
        {"name": "Split Block", "unit": "EACH", "mat": 13.49, "lab": 0},
        {"name": "Light Block", "unit": "EACH", "mat": 11.72, "lab": 0},
        {"name": "UL Block", "unit": "EACH", "mat": 21.51, "lab": 0},
        {"name": "Jumbo Block", "unit": "EACH", "mat": 11.72, "lab": 0},
        {"name": "Dryer Vent 4\"", "unit": "EACH", "mat": 23.81, "lab": 0},
        {"name": "Meter Block", "unit": "EACH", "mat": 36.64, "lab": 0},
        {"name": "12x12 Louvers", "unit": "EACH", "mat": 33.47, "lab": 0},
        {"name": "12x18 Louvers", "unit": "EACH", "mat": 49.11, "lab": 0},
        {"name": "22\" Octagon", "unit": "EACH", "mat": 75.78, "lab": 0},
        {"name": "34x22 Half Round", "unit": "EACH", "mat": 118.39, "lab": 0},
    ]},
    {"title": "Miscellaneous Accessories", "ascend": False, "items": [
        {"name": "Deal Seal Silicone", "unit": "TUBE", "mat": 7.54, "lab": 0},
        {"name": "Boss Silicone", "unit": "TUBE", "mat": 8.23, "lab": 0},
        {"name": "OSI Quad", "unit": "TUBE", "mat": 9.86, "lab": 0},
        {"name": "OSI Quad Max", "unit": "TUBE", "mat": 10.79, "lab": 0},
        {"name": "1/4\" Fan-Fold Insulation", "unit": "Bundle", "mat": 33.13, "lab": 0},
        {"name": "3/8\" Fan-Fold Insulation Foil", "unit": "Bundle", "mat": 22.13, "lab": 0},
        {"name": "Rain Drop 9'x125'", "unit": "Bundle", "mat": 311.23, "lab": 0},
        {"name": "House Wrap 9' x 100'", "unit": "Roll", "mat": 104.05, "lab": 0},
        {"name": "Green Guard Tape", "unit": "Roll", "mat": 26.86, "lab": 0},
        {"name": "1 1/4\" White Trim Nails 1 lb", "unit": "BOX", "mat": 9.00, "lab": 0},
        {"name": "1 3/4\" White Trim Nails 1 lb", "unit": "BOX", "mat": 10.33, "lab": 0},
        {"name": "Zip Screws (Qty. 100)", "unit": "Bag", "mat": 10.75, "lab": 0},
    ]},
    {"title": "Tear-Off / Clean Up (Labor)", "ascend": False, "items": [
        {"name": "Tear-Off Existing Siding", "unit": "SQ", "mat": 0, "lab": 0},
        {"name": "Wood Shake Tear-Off", "unit": "SQ", "mat": 0, "lab": 0},
        {"name": "Clean Up / Haul Away Debris", "unit": "JOB", "mat": 0, "lab": 0},
        {"name": "Dumpster Rental", "unit": "EACH", "mat": 0, "lab": 0},
    ]},
    {"title": "Misc. Labor Only", "ascend": False, "items": []},
    {"title": "Misc. Labor & Material", "ascend": False, "items": []},
]
